### PR TITLE
Perf: Improve river check function

### PR DESCRIPTION
**Pull request by developer-8**
This PR intends to improve the `is_horizontal_border_river` function, which is currently not working optimally.
Currently at `border_river_width = 44` the function call the `get_noise` function for a range of `pos.y` from -66 to 66. But effectively for `pos.y` from -66 to 0, since this function is never called for positions from the South side.
This PR makes it so that the `get_noise` function only call for the possible noise range `pos.y` from -26 to -22 at noise size of 4.
The increase in performance should be insignificant, as the function is called only at the beginning when generating the map and when checking landfill. 

### Tested Changes:
- [x] I've tested the changes locally alone.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by Ragnarok77-factorio** [comment]
The map generation is much better nowadays (but when I test stuffs, I cant game speed too fast due to map gen).
Any improve on that side is still nice, and maybe it could help too when players explore far.

**Comment by Ragnarok77-factorio** [comment]
For the PR, logic wise I'm really unsure of fully understand it so (just the algo I mean since I like the idea of PR, any perf PR is good PR).. Code wise I dont see any issue, tested it locally, no issue found too.

**Comment by developer-8** [comment]
On this image red is the range of `pos.y` for which the `get_noise` function is called, before and after the changes
improve-border-river
Hope its help @Ragnarok77-factorio

**Review by Ragnarok77-factorio — DISMISSED** [review]
OK, nothing much to add code wise.

**Comment by developer-8** [comment]
The merge conflicts after the branch change have been resolved and this PR is ready for review.
The merge commit removes some whitespace, there's nothing I can do about it.

**Review by Ragnarok77-factorio — APPROVED** [review]
Already approved it in the past, ok with it still. And it's fine for the whitespaces.
Tested it locally, noticed nothing.

**Review by TheBigZet — APPROVED** [review]

**Pull request merged**
