### PR TITLE
now can't join team if reroll didn't end.

### PR DESCRIPTION
**Pull request by PlayerNoon**
### Brief description of the changes:
blocks possibility to join team if reroll voting is active
display message for a player when click join. 

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by clifffrey** [comment]
What is the motivation for this change?  It is not clear to me if this is a good idea or not.  I think that perhaps there should be something in #game-vote about it to see if the community wants this behavior.

**Comment by PlayerNoon** [comment]
i call it a bug.

**Comment by PlayerNoon** [comment]
poll result 
https://discord.com/channels/823696400797138974/823771211421974579/1266449885041922101

**Review by clifffrey — APPROVED** [review]
Thank you for making the poll and making the change!

**Pull request merged**
