### PR TITLE
Remove more unused modules

### PR DESCRIPTION
**Pull request by TheBigZet**
### Brief description of the changes:
Part 2 of debloating the codebase

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [x] I've not tested the changes.

### CODE REVIEW

**Review by developer-8 — APPROVED** [review]
Interesting code, but not used anywhere.

**Comment by Ragnarok77-factorio** [comment]
Yes, I agree we should not have any useless code in bb (ie a code never called).

It's always very annoying when you use search and end up on code not used. And it's not good for new devs (they get confused for nothing)

**Review by Ragnarok77-factorio — APPROVED** [review]
Nothing is called in these functions, tested it very quickly, could start and restart a map so it should be fine

**Review by XVhc6A — APPROVED** [review]
yes!!!!!

**Comment by Ragnarok77-factorio** [comment]
Tested live on main bb, no issue found, ready for merge

**Pull request merged**
