### PR TITLE
Trust based on permissions

### PR DESCRIPTION
**Pull request by TheBigZet**
### Brief description of the changes:
Trust is now based on permissions 

### Tested Changes:
- [X] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by TheBigZet** [comment]
Sigh, idk why there are the 2 first commits...

**Comment by developer-8** [comment]
What are the desired consequences of these changes?

**Comment by TheBigZet** [comment]
Hopefully better working system. 
There's a lot of holes in the current system, so maybe permissions will work better as they are integral part of the game.
Also maybe it will be less laggy as we stop checking every placed entity

**Comment by developer-8** [comment]
It's weird experience. Untrusted player can place ghost, which if it splitter can deconstruct existing belts. But cant copy, paste, create blueprint or cancel deconstruct, cant remove ghosts by deconstruct only by hand

**Comment by TheBigZet** [comment]
Exacly, permissions would unify it

**Comment by developer-8** [comment]
Do you mean that you intend to make more changes? I received the described experience from this PR

**Comment by TheBigZet** [comment]
Right, sorry.
The limitation here is comming from non-existing permission definition for "hand ghosting"
I assumed that this wouldn't be a problem as it's difficult to cause mass harm by hand.
However I didn't take into consideration spliter placement described by you

**Comment by Ragnarok77-factorio** [comment]
Maybe just retrieve the old part to prevent handghosting and only that part ?

I wonder how this PR interact with current new anti landfill update though too (untrusted cant landfill), no conflict ? I guess the best would be just that this branch retrieves recent changes of develop and test it 🤔

**Comment by Ragnarok77-factorio** [comment]
Just for the trace, impossible to prevent hand ghosting with permission, it's a parameter of build input_action and you cant just forbid build, otherwise they can't build (not only hand ghosting but all kind of buildings), so only choice is to use on built entity event again for that part

**Pull request closed without merging**
