### PR TITLE
Flamers firestream nerf

### PR DESCRIPTION
**Pull request by derkachdaniil**
### Brief description of the changes:
nerfing stackable flamethrower damage, decreasing oil consumption at the same rate (90%in the example)

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by mysticamber — CHANGES_REQUESTED** [review]
No hardcoded values in init.lua please. Should be in tables.lua

**Comment by derkachdaniil** [comment]
can move values in tables.lua as an optional pr - just like it was with bullets.

**Comment by guymaor86** [comment]
why not do it in this pr?

**Comment by derkachdaniil** [comment]
don't want to test all stuff again after changing PR. and new PR (if i understand git stuff correctly) not gonna be auto-merged to version, that's already using current PR version. if all of this is not a problem - can make changes here

**Comment by guymaor86** [comment]
All of that should not be a problem
You can make as many commits as you want with git
If theres an issue and a PR can't be merged it'll say it has conflicts

**Comment by Ragnarok77-factorio** [comment]
Old PR , closed (needs vote approval anyways)

**Pull request closed without merging**
