### PR TITLE
Bugfix : total playtime is now logged

### PR DESCRIPTION
**Pull request by Ragnarok77-factorio**
### Brief description of the changes:
Playtime has been broken for a very long time, it requires to be stored on the server, here is the PR that makes it possible, by showing messages in server log.
I also cleaned a bit some unused code.

It will upload playtime to server every 15 minutes, or when a player leaves.
It will set the total playtime when a player joins.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by XVhc6A** [comment]
I think if you do it this way, you will need to manage the current time played when players leave the game.  Otherwise it seems they could join in the beginning, leave for 2 hours and get credit for all of it.

**Review by XVhc6A — CHANGES_REQUESTED** [review]
see previous comment

**Comment by Ragnarok77-factorio** [comment]
I don't understand @XVhc6A what do you mean..? 

It's like comfy : 
If you are online, the time on server is logged
If you are not online, it doesn't get logged
And time is logged when you leave the server, playtime is set when you join the server, and time of being online is logged every 15 minutes for all players online..

**Review by XVhc6A — APPROVED** [review]
Looks great! I see now the previous comfy integration.

**Pull request merged**
