### PR TITLE
Small code cleanups, remove legacy/old commands

### PR DESCRIPTION
**Pull request by XVhc6A**
### Brief description of the changes:
The following description has been edited.  The PR is significantly less aggressive.

remove commands:
* spaghetti
* generate_map
* dump_layout
* creative
* delete-uncharted-chunks
* force-map-reset

Remove commands/misc.lua, add commands/instant_map_reset.lua
See commits for more information.

The community should be notified somehow that force-map-reset is replaced with instant-map-reset.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by TheBigZet** [comment]
I use VSCode, so that `.toml` file would be useless for me anyway

**Comment by XVhc6A** [comment]
I think we should standardize the formatting, but if you're opposed that's fine.

**Comment by developer-8** [comment]
Why change `require` to `require()` ? What effect from it ?

**Comment by Ragnarok77-factorio** [comment]
Conflicts needs to be resolved then we can finally test it on bb server, for the require change, ugh I don't know this one. Should it be reverted, should it be kept..?

**Comment by XVhc6A** [comment]
This is rebased on master. 

I vote for keeping ( ) after require calls, but that's only because I'm not used to lua.

**Comment by developer-8** [comment]
I vote for against  ( ) after require calls

How will .stylua.toml work for other contributors who do not have this plugin installed?  will XVhc6A reformat all the code from time to time?

**Comment by XVhc6A** [comment]
I just added a Github Actions workflow to this, and have it checking the formatting for all, and for changed only files.

I don't think it's necessary to enforce people to do it themselves, and i'm happy to do it for anyone that asks, and I don't think it's something that we should restrict merging on.  More of just slowly making sure that things move in the 'cleaner' direction moving forward.  Should the committer feel the urge to update themselves, the github actions logs provide diffs that can be copied as well.

**Comment by XVhc6A** [comment]
I have significantly reduced the scope of this PR. Now it just gets rid of old unused commands and doesn't try to be fancy about formatting.  see the commits and their messages for more information.

**Review by clifffrey — APPROVED** [review]
Thank you, this is a great cleanup

**Pull request merged**
