### PR TITLE
Rework of biter terrain texture to be factorio 2.0 compatible

### PR DESCRIPTION
**Pull request by cogito123**
### Brief description of the changes:
As per [#fff-383](https://factorio.com/blog/post/fff-383) it's possible to mine landfill in Factorio 2.0, so let's get rid off it from biter area. Because landfill was helping to shade nuclear-ground the entire color palette needs to be changed as well to not look ugly.
Additionally, new tool appends header to the file so that texture can be always reproduced. I published the initial version of the tool [here](https://github.com/cogito123/bb-tools)

terrain

### Tested Changes:
- [X] I've tested the changes locally

### CODE REVIEW

**Comment by Ragnarok77-factorio** [comment]
Not even sure how we can review that code wise to be honest.
We'll test it on main bb server.

**Comment by cogito123** [comment]
You could reformat it with some online tool, your text editor or other dedicated tool to view it in more structured way. It's compressed as much as possible, because it's representation of an image deserialized as massive lua array.

**Comment by developer-8** [comment]
I think it's too early to phase out landfill.  Sometime new texture blends too good with non biter area
Screenshot from 2024-01-06 12-22-57
Need to test on server to collect more feedback

**Comment by cogito123** [comment]
> Do you think there might be a way to reduce the size of the file? 1/2 mb seems super excessive. ( i know it was big before this PR, but jw)
> 
> overall though, if you don't want to reduce the file size, I approve, tested in game and it worked.
If I reduce size I have to sacrifice on resolution and then it becomes visibly repetitive.

> I think it's too early to phase out landfill. Sometime new texture blends too good with non biter area. Need to test on server to collect more feedback
Why is this an issue? In fact I wanted to make another change in the future that makes biter area blend better around the edges

**Comment by developer-8** [comment]
Not sure if it issues. it just not looks like it was biters area at all 
image
image

**Comment by cogito123** [comment]
OK, I see what you mean. Some options that I see at the moment.

1. You could suggest some other color palette. I went through many combinations, but didn't found anything better. Additionally to much of the same color, doesn't look visually appealing and you need to have at least 2 dominant colors to mix together and shade. Factorio default tile set is also very limited in what you can do. Grass doesn't look great either.
2. Not only generate tile set positions, but also positions of biter nests and cluster then together away from sand tiles. This could enchant visual appeal by looking more organic. IIRC nest placement is completely random.

I like option 2, what do you think?

**Comment by clifffrey** [comment]
This code has been running since January

**Pull request merged**
