### PR TITLE
Ura ammo and kovarex researched when ura processing is researched, same for gate with wall

### PR DESCRIPTION
**Pull request by Ragnarok77-factorio**
### Brief description of the changes:
Uranium ammo research and kovarex are researched automatically only when uranium processing is researched, gate is researched when wall is researched

Discord vote links : 
https://discord.com/channels/823696400797138974/823771211421974579/982710508312477777
https://discord.com/channels/823696400797138974/823771211421974579/994194727433941062
https://discord.com/channels/823696400797138974/823771211421974579/994459774630510712

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by TheBigZet** [comment]
Make it after uranium processing

**Comment by Ragnarok77-factorio** [comment]
> Make it after uranium processing

Thanks, forgot the vote changed after discussion and it was ura processing and not sulfur processing, fixed it. @TheBigZet

**Review by TheBigZet — APPROVED** [review]
Ideally we would have returns after each if (or else if construction), but that's just 2 checks per game so leave it :D

**Comment by Ragnarok77-factorio** [comment]
@TheBigZet : 
After z-em remark, I added also kovarex auto unlock, and updated to elseif since I was updating code.. (even if in this case, it really doesn't matter, why not update since I was updating code 1 line above..)

**Review by TheBigZet — APPROVED** [review]

**Pull request merged**
