### PR TITLE
translation simplified Chinese

### PR DESCRIPTION
**Pull request by dwightkung**
### Brief description of the changes:
add simplified Chinese locale to BiterBattles

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by Ragnarok77-factorio — CHANGES_REQUESTED** [review]
Not sure of me but (feel free to correct, but I don't understand how you tested it since when I switch to zh-CN language, it's not translated..) : 
-You need to create a zh-CN folder inside "locale" folder
-Rename zh-CN file to locale.cfg

Then it should be fine.

With the current PR : 
image

With the change I said : 
image


Also the first 2 lines are not translated, is it on purpose ?

For the traduction I can't judge, feel free to correct me if  I'm wrong

**Comment by dwightkung** [comment]
Thanks for testing.
You are right, I should create a folder first.
In fact, I do make the zh-CN folder in offline test, but when I edited on the github, I just copy and paste. 
Sorry about that, I am new to github, just registered yesterday.
And I suppose people get access to dicord could read English, so i didnt translate the first 2 lines. I will finish that part since you point it out, just in case.
Thanks for your testing again!

**Comment by Ragnarok77-factorio** [comment]
No problem and welcome ! :)

**Comment by Ragnarok77-factorio** [comment]
Closing as it's very old, if the need is back, feel free to make a poll on discord first to get it approved by community then we can deploy it

**Pull request closed without merging**
