### PR TITLE
Balance mutagen values for 2.0

### PR DESCRIPTION
**Pull request by cogito123**
### Brief description of the changes:
Changed them according to poll vote

### CODE REVIEW

**Comment by RedRafe** [comment]
Space science got nerfed because RCUs were removed, and utility got buffed because of what recipe change?

**Comment by cogito123** [comment]
It's all according to vote result in #game-vote channel

**Review by clifffrey — CHANGES_REQUESTED** [review]
Looks great.

I'd change the 1% threshold in the failing test to 2% - it was arbitrary to begin with.

**Comment by cogito123** [comment]
OK, adjusted test to 2%

**Review by clifffrey — APPROVED** [review]

**Pull request merged**
