### PR TITLE
New gui

### PR DESCRIPTION
**Pull request by TheBigZet**
### Brief description of the changes:
Main gui overhaul:
- Unified all versions (first join, in-team and spectator); now they all come from first gui with small modifications instead of nuking and rebuilding
obraz 
obraz
obraz

- Moved rejoin and playerlist buttons to solve confusion related to "being able to join only south"
- Playerlist is now just a single label for all players instead of separated ones for each player; Additionally it can be hidden in first-join gui
- Replaced the nuke-rebuild system with simple caption updates; additionally the values to be refreshed are stored in new `gui_data` table, to ensure that we make as little operations as possible
- Moved all top buttons creation to `main` to ensure proper creation and require order
- Replaced `gui_styles.lua` with more functional module in `utils.lua`; Now it supports all options from LuaStyle
- Replaced `show_pretty_threat()` with `metric_notation()` in `utils.lua`; Possibly to be improved

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by 1pulse** [comment]
I think ppl can't join sides, need an admin to manage teams only ok in special games

**Comment by Ragnarok77-factorio** [comment]
@TheBigZet @1pulse  : 

I tested it locally, if it's the first ever game, seems like an admin needs to join to unlock it, but it seems like it's the same for the current bb version, then once the game ends, players can join even without an admin... Otherwise, I could join, no error message, could send science, but barely tested it, would need to be tested live on bb to be honest for better test.

I haven't look code yet though.

**Comment by developer-8** [comment]
new gui
Are the underlined changes in fonts, colors and text intentional?

**Review by developer-8 — CHANGES_REQUESTED** [review]
Game time does not change

**Pull request closed without merging**
