### PR TITLE
Show big threat value with k or m at end of text

### PR DESCRIPTION
**Pull request by Ragnarok77-factorio**
### Brief description of the changes:
Show big threat values with "k" or "M" : 
image

Discord vote link : https://discord.com/channels/823696400797138974/823771211421974579/995801476997840976

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by developer-8 — CHANGES_REQUESTED** [review]
Take into account also the negative threat

**Comment by Ragnarok77-factorio** [comment]
> Take into account also the negative threat

@developer-8 Wow good one, I didn't think of negative threat for unknown reason, added it : 
image

**Comment by Ragnarok77-factorio** [comment]
I don't know how to close your suggested changes, or if there is nothing to do on github, but code updated

**Comment by developer-8** [comment]
Set a big threat and go kill some biters. The dots appear for a moment when the threat is reduced.
threat bug

**Comment by Ragnarok77-factorio** [comment]
> Set a big threat and go kill some biters. The dots appear for a moment when the threat is reduced. threat bug

Good catch, I didn't think of farming biters to see how it reacts, should be fine now no? I made a function instead since it was going to be called from different places (create main gui and refresh threat). @developer-8

**Review by developer-8 — APPROVED** [review]
Works well

**Comment by thulle** [comment]
> if math_abs(threat_value) > 1000000 then

shouldn't these comparisons be greater than or equal? 1000000 is as many digits as 1000001, but only the latter triggers the M prefix.

**Comment by Ragnarok77-factorio** [comment]
> > if math_abs(threat_value) > 1000000 then
> 
> shouldn't these comparisons be greater than or equal? 1000000 is as many digits as 1000001, but only the latter triggers the M prefix.

You are correct, I updated it. @thulle

**Pull request merged**
