### PR TITLE
special games panel: add easy access for modifiers from LuaForce.

### PR DESCRIPTION
**Pull request by PlayerNoon**
### Brief description of the changes:
Bunch of modifiers. 
You can find them here.
https://lua-api.factorio.com/latest/ 
in search bar type "modifier" / "bonus". results only from LuaForce.
All of them have tooltip with possible input values.

image

all modifiers applied are visible in Bonuses panel. all of them reset after round ending.
image

### Tested Changes:
- [x] I've tested the changes locally
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by TheBigZet — CHANGES_REQUESTED** [review]
What does "most force modifiers" mean?
Does it reset after round ending?

**Comment by PlayerNoon** [comment]
> What does "most force modifiers" mean? Does it reset after round ending?

https://lua-api.factorio.com/latest/ type modifier / bonus. results for LuaForce.
i didn't test if all of them resets after round ending. I will tell when i finish it, probably one day.

**Comment by PlayerNoon** [comment]
> What does "most force modifiers" mean? Does it reset after round ending?

ok tested. all off them resets.

**Comment by TheBigZet** [comment]
Those modifiers are easy enough to set from the command line in my opinion

**Comment by PlayerNoon** [comment]
sure wahtever. :)

**Pull request closed without merging**
