### PR TITLE
shout-fix: fix shout logging so that non admin shouts get logged too

### PR DESCRIPTION
**Pull request by mysticamber**
### Brief description of the changes:
---Fill in---

### Tested Changes:
- [x ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by 1pulse** [comment]
If u tested Im ok. Thx!

**Comment by 1pulse** [comment]
Hum I cant merge It show me errors

**Comment by 1pulse** [comment]
This branch has conflicts that must be resolved … can u check it?

**Comment by mysticamber** [comment]
> This branch has conflicts that must be resolved … can u check it?

I was hoping it wouldn't happen. I've resolve the conflicts :)

**Comment by 1pulse** [comment]
Thx again

**Pull request merged**
