### PR TITLE
Enable profiler

### PR DESCRIPTION
**Pull request by TheBigZet**
### Brief description of the changes:
Enabled profiler module so that we can start it during endgame to get a reference point for further updates.
Added dumping to file

Downsides:
Seems to amplify lag spikes (eg for map gen)

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by Ragnarok77-factorio — APPROVED** [review]
Tested it, OK. Nothing much to add about it.

**Comment by mysticamber** [comment]
I dont mind putting this in but i'm a bit worried ppl will forget to stop the profiler. Is it possible to have an indicator somewhere? or have it autostop at some point (on game over or something).

**Comment by TheBigZet** [comment]
> I dont mind putting this in but i'm a bit worried ppl will forget to stop the profiler. Is it possible to have an indicator somewhere? or have it autostop at some point (on game over or something).

FPS drop will be an indicator :P But yea, I guess that's a good idea

**Comment by Ragnarok77-factorio** [comment]
I wonder @TheBigZet , would it be possible to add just a game.print message when it's starting and stopping? Saying like "profiler was enabled to investigate performance of code, fps ups might drop" or something. So players know when it's being enabled.

**Comment by Ragnarok77-factorio** [comment]
Mh, I can't suggest change far from your code..
Would probably do something like that:
Header :
`
local Color = require 'utils.color_presets'`

In startCommand function : 
`
	local player = game.player
	if not player or not player.valid then return end
	if not player.admin then
			player.print('[ERROR] You need to be admin', Color.fail)
			return
	end
	game.print('Profiler started by ' .. player.name .. '(fps/ups will drop)')`

In stopCommand function : 
`
	local player = game.player
	if not player or not player.valid then return end
	if not player.admin then
			player.print('[ERROR] You need to be admin', Color.fail)
			return
	end
	game.print('Profiler ended by ' .. player.name)`

=>Message for everyone, restriction to admin only (realized that on dev branch, everyone can start profiler, which is great for me but... depending on player...). @TheBigZet

**Review by Ragnarok77-factorio — APPROVED** [review]
Ok with change, just a bit worried about adding a on tick function but I guess it's fine for what it's doing..

**Pull request merged**
