### PR TITLE
Global speaker won't nuke speakers in jail and jail speaker heard by all forces

### PR DESCRIPTION
**Pull request by Ragnarok77-factorio**
### Brief description of the changes:
To avoid that the button "destroy all global speakers" destroys the ones in jail, I set it to skip gulag(jail) surface. Another solution would have been not to set speaker to global in jail but then if the jailed player move (there was an approved  request to allow them moving with a behe hunting them), in this case they could run away from the music.
+ updated changelogs
+ duplicate song for south/north and not just spectator, so now all forces can hear it, not only spectator (fix https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/249)

### Tested Changes:
- [x] I've tested the changes locally.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by Ragnarok77-factorio** [comment]
Also added https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/249

**Comment by developer-8** [comment]
Why are all variables global in `createTrollSong`?

**Comment by Ragnarok77-factorio** [comment]
Mistake, fixed it @developer-8 , now all should be local.

**Review by TheBigZet — COMMENTED** [review]
Jail song was changed around in #264

**Comment by Ragnarok77-factorio** [comment]
> Jail song was changed around in #264

Thanks for information
==
@TheBigZet  : Finished resolving the conflict and fixing it back like before.

**Comment by Ragnarok77-factorio** [comment]
Okay, little issue on my git, needs to fix, back to draft.

**Pull request merged**
