### PR TITLE
Change river function

### LINKED ISSUE #174: Pre-generated gun-turrets can end up in river
If spawn turrets are generated around silo, some of them might end up in area that is later overwritten with water tiles. This leaves positions within river as one of the targets and can cause problems with AI pathing

### PR DESCRIPTION
**Pull request by developer-8**
The main change in this PR is that the water around the island is now considered part of the river and is generated with it.
Previously, the water around the island (spawn circle) was drawn on top of everything, now only the island is drawn this way.
Features
- Only one function to check the river, no need to do extra check on spawn circle
- The water around the island is now exactly 39 tiles as specified
- No fish under island
- Added a single check for the river when generating the starting area, which should fix #174 for sure

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by TheBigZet** [comment]
How does it correspond to #304 ?
Required / conflicting / unrelated?

**Comment by developer-8** [comment]
unrelated

**Comment by developer-8** [comment]
Previously river function(`is_horizontal_border_river`) was was straight line.
With this PR river function include circle of water around island.
river

**Review by TheBigZet — APPROVED** [review]

**Comment by developer-8** [comment]
@TheBigZet  Conflicts resolved

**Pull request merged**
