### PR TITLE
move on_player_mined_entity to control-dispatch

### PR DESCRIPTION
**Pull request by XVhc6A**
### Brief description of the changes:
This is a partial PR from https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/410
The purpose of this is to simplify the codebase, and in doing so, make the gui-rewrite easier. By pushing this to a separate PR, it should be easier to review and evaluate.

The way Event.add is used now leads to confusion w/r/t the order of operations, as well as makes debugging (and thus development) slower.  By incrementally moving single events to this method of dispatch, we will enable ourselves to delete more code, and expedite the gui-rework.

I tested this code locally.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Review by clifffrey — APPROVED** [review]

**Comment by clifffrey** [comment]
I just wanted to understand/confirm something that is currently not in the commit description. Specifically, what is the underlying motivation for this?  Why is it better to have things in control dispatch?  I assume the answer is something like the following (which could be added to the commit message)

Putting things in control-dispatch is important because only a single lua event handler can be registered for each type of event. If multiple parts of the code want to trigger something on on_player_mined_entity, then it is necessary that there is only one call to `Event.add(defines.events.on_player_mined_entity, ...)`, and it makes sense for that to be in a centralized location, like control-dispatch.

**Comment by XVhc6A** [comment]
There are multiple reasons, I will briefly list them in no particular order.
* the current implementation is despised by the factorio devs.  They have been reluctant to help with fbb code in the past because they don't think abstracting the on_event framework is smart for a variety of reasons.  There are multiple posts from them about this on the forums, I think the spiciest is wrt to the stdlib library, but the message is clear from them from all of those posts. 
* Currently, when you have problems, the stacktrace doesn't go back any scopes, just up to Event.
* This is essentially a niche framework with complex requirements, for a niche set of code. I hope that by simplifying it to make it more like standard lua, and more like standard factorio code, we can encourage more contributors.
* every event currently has its own set of if statements, we can combine them with single dispatch to hopefully improve performance.
* When debugging event problems, order is currently basically completely unknown.  single dispatch makes it visible in the code.
* I had a minimal gui rewrite code setup, but I was having a ton of problems with the way that the events were being triggered in relation to eachother.  I gave up eventually because every time I changed something, the events would happen out of order and buttons would move around.  I don't remember the specifics, but it was frustrating.

**Comment by clifffrey** [comment]
I can merge this once merge conflicts have been resolved

**Comment by XVhc6A** [comment]
I've re-written this to focus just on the centralization efforts.

Removing the Event framework without a replacement would effectively render all special games code useless.  Special games are becoming more and more common so I think we should focus on centralization first, then gui-rewrite, and then look into removal of the Event framework and any other legacy code.

**Review by clifffrey — APPROVED** [review]

**Comment by developer-8** [comment]
`/temp/currently-playing/maps/biter_battles_v2/main.lua:144: attempt to call global 'maybe_set_game_start_tick' (a nil value) in ...y)/temp/currently-playing/maps/biter_battles_v2/main.lua:143`

**Pull request merged**
