### PR TITLE
Compress Captain Countdown images (3.1MB -> 860KB, 0.27x size) 

### PR DESCRIPTION
**Pull request by vadcx**
Images were part of commit https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/commit/cdbe6a9a764917fec03451961e65a537be95ed49

https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/406

PS: Note that the see-through transparency artifacts were part of
original images.
PPS: WHERE are the original images? Because that part looks worse than what pngquant did to them. With original images we could've improved their quality too.
PPPS: Of course this doesn't reduce the repository size

This is important, because unlike Scenario preview image.png, these images are
transferred to each player loading the multiplayer map. Therefore we'll see 2
MiB less traffic per joining player.

Original PNG: 413.5 KiB (it's already optimized, within 1% of optipng)

Guetzli: 58 KiB - with JPEG quality = 84 (minimum allowed)... but needs an extra
alpha file for blending, JPEG doesn't support transparency.

PNGQuant color depth reduction:
   - 2 bits cut off: 146.6 KiB
   - 3 bits: 139.5 KiB
   - 4 bits: 113.4 KiB. The difference is barely noticable

Only that Firefox doesn't render transparency as transparent anymore, it's full
white.

Even if transparency layer was 100% free by size, the best that can be achieved with
JPEG at this setting is another 500 KiB reduction MAX. The resulting savings will end up much smaller
once we include blending files/layers.

Another approach is to pack them all in a sprite map. I was impressed with
pngquant's results so maybe the color space limitation (8-bit palette) won't be
too noticable, although some numbers have different color palettes. Even then,
optipng reports most images now have between 68-156 colors. There's the space to
cram them in. Also there's the `--quality` option I didn't touch, I don't want
compressed images to be much worse, they're alright now.

```shell
cd png;
rm -rf -- ./pngquant-out 2>/dev/null;
mkdir pngquant-out 2>/dev/null;
echo 'down to approx 100 KiB'
for num in *.png; do pngquant --speed 1 --posterize 4 - >pngquant-out/"$num" < "$num"; done

cd ./pngquant-out;
echo 'Another 1% savings...'
ls -1 . | xargs -L 1 -P 8 optipng -o7 -zm1-9
```

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by clifffrey** [comment]
Have you tried asking on the discord server, in #dev-git, if anyone knows where the original images came from or has a copy of them?

**Comment by vadcx** [comment]
Good idea. @Ragnarok77-factorio were these countdown images AI generated? I've found a bunch of stock images that all match this randomly similar factory/techno style on Google Image search

**Review by clifffrey — APPROVED** [review]
Well, perhaps we will eventually have better source images, but this change is clearly a huge step forward even on its own, so I'll take it for now.

**Comment by clifffrey** [comment]
original numbers are probably in here, in case you still want the originals https://cdn.discordapp.com/attachments/1156244894428430387/1174485891390132294/numbers.zip?ex=6632cb39&is=66205639&hm=b24451392bb7bd21b5fe78217c0c349a4b54de6a2c22f715e01e0a58e0b26a9e&

**Pull request merged**
