### PR TITLE
Fix captain text render

### PR DESCRIPTION
**Pull request by direwolfclaw**
### Brief description of the changes:
---Fill in---
This turned out to be quite easy.

The captain rendering is all being stored in global.special_games_variables.rendering, with keys of a name string (textId) and values of uint64 rendering IDs returned by rendering.draw_text() and analogous methods. As such, no new book keeping is required, just looping over these objects and destroying them specifically.

The one caveat is that the current implementation would destroy all special game rendering that is correctly registered within global.special_games_variables.rendering. I'm unsure if anyone actually uses it (I do not use it and barely knew the structures existed).

To make it compatible with this case, one can add `if string.sub(textId, 1, 7) == 'captain' then` into the new clear_captain_rendering() method to only remove rendering with matching textIds. This does commit the captain machinery to uniformly use this format for naming all text, which is why I opted not to do it that way (and would be ever so slightly slower).

I can test later but wanted to take care of this. Recommend merging all the little commits, they are mostly silly typos and backtracking with web-based github.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by clifffrey** [comment]
Can you verify that, in a single-player game, you can start a captains game?  You can use `/cpt-test-func` to set it up so that you can start the game - just do captainless community pick or something, and then do something that will redraw the text, i.e. `/replaceCaptainNorth` or whatever.  Then you can check the "I've tested the changes locally" checkbox above.

**Comment by direwolfclaw** [comment]
It works fine.

**Review by clifffrey — APPROVED** [review]
Thank you for the change!

**Comment by clifffrey** [comment]
Can you fix the lint issues?  You should be able to run `stylua .` in the directory to fix everything.  If you cannot do this, let me know, and I can do it for you.

**Comment by direwolfclaw** [comment]
I thought you had said it was automatic when this system was implemented, so I ignored the style stuff. I am substantially less enthusiastic about it now that I know how it works. I'm not sure how I amend the code on github at this stage of the PR anyway.

**Comment by direwolfclaw** [comment]
I will say that I think this PR itself is one layer of fault tolerance - it should check if not global.special_games_variables before checking for its member .rendering. It gets to one of the things about booleans in lua I don't quite understand.

Does `if not A or B` mean `if (not A) or (B)` or does it mean `if not (A or B)`. I believe it's the former, in which case the offending line should read
`if not global.special_games_variables or not global.special_games_variables.rendering then
return
end`

**Comment by direwolfclaw** [comment]
OK that was easy. I didn't realize it would just update the PR if I made commits to the branch.

**Pull request merged**
